/* ============================================================================
   One-off recipe import — Task 3.

   Reads data/recipes.json and runs it through the SAME importBase44Json the app
   uses (src/lib/importBase44.js), then writes the resulting ingredients + recipes
   into Supabase. Because both the app and this script import that one module, the
   stored data matches the prototype's in-memory data exactly.

   Two ways to load:
   1. Direct (needs network egress to *.supabase.co allowed):
        node --env-file=.env.local scripts/import-recipes.mjs
      Re-running requires --force (clears ingredients + recipes first), so you
      never silently duplicate or wipe real data.
   2. Emit SQL to paste into the Supabase SQL Editor (no network needed here):
        node scripts/import-recipes.mjs --emit-sql
      Writes supabase/import_recipes.sql (idempotent: ON CONFLICT DO NOTHING).

   Caveats carried through from the source (see CLAUDE.md): every recipe defaults
   to yield 10kg, every ingredient cost is £0, a few source typos remain, images
   are Base44 URLs, and allergen/dietary tags are auto-suggested (not legal).
   ============================================================================ */
import { readFileSync, writeFileSync } from "fs";
import { importBase44Json } from "../src/lib/importBase44.js";

const force = process.argv.includes("--force");
const emitSql = process.argv.includes("--emit-sql");

// --- transform via the shared importer (empty base = real recipe ingredients only) ---
const text = readFileSync(new URL("../data/recipes.json", import.meta.url), "utf8");
const { recipes, ingredients } = importBase44Json(text, []);

const ingRows = ingredients.map((i) => ({ id: i.id, name: i.name, unit: i.unit, cost: i.cost }));
const recRows = recipes.map((r) => ({
  id: r.id,
  name: r.name,
  category: r.category || null,
  department: r.department || null,
  dept2: r.dept2,
  notes: r.notes || "",
  allergens: r.allergens,
  dietary: r.dietary,
  hero: r.hero,
  images: r.images,
  yield_kg: r.yieldKg,
  yield_unit: r.yieldUnit,
  expected_sec: r.expectedSec,
  steps: r.steps,
}));
const stepCount = recipes.reduce((a, r) => a + r.steps.length, 0);
console.log(`Transformed: ${recRows.length} recipes, ${ingRows.length} ingredients, ${stepCount} steps.`);

// ---------------------------------------------------------------------------
// Mode 2: emit a SQL file to run in the Supabase SQL Editor (no network here).
// ---------------------------------------------------------------------------
if (emitSql) {
  const q = (v) => {
    if (v === null || v === undefined) return "null";
    if (typeof v === "number") return String(v);
    return "'" + String(v).replace(/'/g, "''") + "'";
  };
  const j = (v) => (v === null || v === undefined ? "null" : "'" + JSON.stringify(v).replace(/'/g, "''") + "'::jsonb");
  const ingValues = ingRows.map((i) => `  (${q(i.id)}, ${q(i.name)}, ${q(i.unit)}, ${i.cost})`).join(",\n");
  const recValues = recRows.map((r) =>
    `  (${q(r.id)}, ${q(r.name)}, ${q(r.category)}, ${q(r.department)}, ${q(r.dept2)}, ${q(r.notes)}, ` +
    `${j(r.allergens)}, ${j(r.dietary)}, ${q(r.hero)}, ${j(r.images)}, ${r.yield_kg}, ${q(r.yield_unit)}, ` +
    `${r.expected_sec}, ${j(r.steps)})`
  ).join(",\n");
  const sql =
`-- Roni's Production Floor — recipe data import (Task 3)
-- Generated by scripts/import-recipes.mjs from data/recipes.json via the app's
-- own importBase44Json, so this matches the prototype exactly.
-- Run in: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
-- ${recRows.length} recipes, ${ingRows.length} ingredients (all £0), ${stepCount} steps.
-- Idempotent: ON CONFLICT (id) DO NOTHING. Ingredients load first (steps reference them).
begin;

insert into ingredients (id, name, unit, cost) values
${ingValues}
on conflict (id) do nothing;

insert into recipes (id, name, category, department, dept2, notes, allergens, dietary, hero, images, yield_kg, yield_unit, expected_sec, steps) values
${recValues}
on conflict (id) do nothing;

commit;
`;
  const out = new URL("../supabase/import_recipes.sql", import.meta.url);
  writeFileSync(out, sql);
  console.log(`Wrote SQL import to supabase/import_recipes.sql (${sql.length} bytes).`);
  process.exit(0);
}

// ---------------------------------------------------------------------------
// Mode 1: write directly to Supabase with the service-role key.
// ---------------------------------------------------------------------------
const url = process.env.VITE_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error("Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY (.env.local).");
  process.exit(1);
}
const { createClient } = await import("@supabase/supabase-js");
const sb = createClient(url, key, { auth: { persistSession: false } });

// --- guard against duplicate/destructive runs ---
const { count: existing, error: cErr } = await sb
  .from("recipes").select("*", { count: "exact", head: true });
if (cErr) { console.error("Could not read recipes count:", cErr.message); process.exit(1); }
if (existing > 0 && !force) {
  console.error(`Aborting: recipes already has ${existing} rows. Re-run with --force to clear and reload.`);
  process.exit(1);
}
if (existing > 0 && force) {
  console.log(`--force: clearing ${existing} existing recipes and all ingredients...`);
  // recipes cascade to store_stock / central_stock / delivery_queue via FKs
  const d1 = await sb.from("recipes").delete().neq("id", "");
  const d2 = await sb.from("ingredients").delete().neq("id", "");
  if (d1.error || d2.error) { console.error("Clear failed:", d1.error?.message || d2.error?.message); process.exit(1); }
}

// --- insert ingredients first (recipe steps reference ingredient ids) ---
const chunk = (arr, n) => Array.from({ length: Math.ceil(arr.length / n) }, (_, i) => arr.slice(i * n, i * n + n));
for (const part of chunk(ingRows, 500)) {
  const { error } = await sb.from("ingredients").insert(part);
  if (error) { console.error("Ingredient insert failed:", error.message); process.exit(1); }
}
for (const part of chunk(recRows, 200)) {
  const { error } = await sb.from("recipes").insert(part);
  if (error) { console.error("Recipe insert failed:", error.message); process.exit(1); }
}

// --- verify counts from the database ---
const [ri, rr] = await Promise.all([
  sb.from("ingredients").select("*", { count: "exact", head: true }),
  sb.from("recipes").select("*", { count: "exact", head: true }),
]);
console.log(`\nDatabase now holds: ${rr.count} recipes, ${ri.count} ingredients.`);
console.log("Done.");
